### ISSUE TITLE
Update productCategories and products.json (Not for grading)

### ISSUE THREAD

**Issue by albright220** [UMM-CSci-3601-S22/it-2-rocinante#31]
New seed and categories to match what Sue has outlined for categories

**Comment by albright220** [comment]
Will also have to update cypress tests that call on specific information of products/update the pantry to reflect new products seed. Will also have to change the pantry cypress tests that call on specific info.

**Comment by albright220** [comment]
Also need to change store selector to add RealFoodHub and Other Store options

**Comment by caidongting0823** [comment]
The product categories and products.json have been upgraded.
